---
# handlers file for redmine

- name: reload systemd
  shell: systemctl daemon-reload
  changed_when: false

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: reload postgres
  service:
    name: postgresql
    state: reloaded

- name: bundler_install
  bundler:
    state: present
    chdir: "/opt/redmine/redmine-{{ redmine_version }}"
  listen: bundler_install

- name: restart redmine
  service:
    name: redmine.service
    state: restarted

- name: restart sidekq
  service:
    name: sidekq.service
    state: restarted

- name: migrate plugins
  shell: bundle exec rake redmine:plugins:migrate
  environment:
    RAILS_ENV: production
  args:
    chdir: "/opt/redmine/redmine-{{ redmine_version }}"
  changed_when: false

